name: Test

on: [push, workflow_call]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .npmrc
      run: cp tools/_.npmrc .npmrc
    - name: Cache node_modules/
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node_modules
    - name: Install node_modules/
      uses: docker://node:14.18.2-alpine3.14
      with:
        args: yarn --silent install --frozen-lockfile
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN_RO }}
    - name: Compile grammars
      run: |
        for name in constraint expression text; do
          node_modules/.bin/jison src/parsers/grammars/$name.jison -m commonjs -o src/parsers/grammars/$name.js
        done
    - name: Run tests
      uses: docker://node:14.18.2-alpine3.14
      with:
        args: node_modules/.bin/jest --coverage
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        junit_files: junit.xml
